# Main Learning Points: Managing Secrets
# Use GitHub Secrets to securely store and access sensitive data like API keys.

name: Manage Secrets Demo

on:
  push:
    branches: [ main ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use a secret to authenticate an API call (simulated here with an echo)
      - name: Use API Key from secrets
        run: echo "Using API Key: $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      # Example: Pass secret to a script (for demo purposes only, avoid exposing secrets in logs)
      - name: Run a script with secret
        run: echo "Simulating API call with key: $(echo $API_KEY | head -c 4)..."
        env:
          API_KEY: ${{ secrets.API_KEY }}

# To use this workflow:
# 1. Add a secret named API_KEY in your repository settings (Settings > Secrets and variables > Actions > New repository secret)
# 2. Place this file in .github/workflows/manage-secrets.yml
# 3. Push to the main branch to trigger the workflow
# 4. Check the "Actions" tab to see the workflow run (secrets are masked in logs)