# Main Learning Points: Docker Image Builds and Pushes
# Automate building and pushing Docker images to a registry.

name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cd-demo-app:${{ github.sha }}

# To use this workflow:
# 1. Set up GitHub Secrets for DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
# 2. Ensure app.js, Dockerfile, and package.json are in your repository
# 3. Place this file in .github/workflows/docker-build-push.yml
# 4. Push to the main branch to trigger the workflow
# 5. Check Docker Hub to see the pushed image