# Main Learning Points: Setting Up a CI Pipeline
# A CI pipeline automates building, testing, and validating code changes.

name: Basic CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (assuming Jest for this example)
      - name: Run tests
        run: npm test

# To use this workflow:
# 1. Ensure you have a Node.js project with package.json and a test script
# 2. Place this file in .github/workflows/ci-pipeline.yml
# 3. Push to the main branch or create a pull request to trigger the workflow
# 4. Check the "Actions" tab in your GitHub repository to see the workflow run